# Generated by Django 6.0.5 on 2026-09-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0002_modelo_completo_y_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('dias_calculados', models.PositiveIntegerField(editable=False, verbose_name='Días Calculados')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
