# Generated by Django 6.0.5 on 2026-09-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Gestión DSI', max_length=100)),
                ('tiempo_sesion_minutos', models.PositiveIntegerField(default=30)),
                ('dias_vacaciones_por_anio', models.PositiveIntegerField(default=15)),
                ('max_intentos_login', models.PositiveIntegerField(default=5)),
                ('minutos_bloqueo_login', models.PositiveIntegerField(default=5)),
                ('modo_mantenimiento', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
