# Generated by Django 6.0.5 on 2026-09-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardias', '0001_initial'),
        ('trabajadores', '0002_modelo_completo_y_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardiaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10)),
                ('aprobado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_asignadas', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Guardia y Turno',
                'verbose_name_plural': 'Guardias y Turnos',
                'unique_together': {('trabajador', 'fecha', 'turno')},
            },
        ),
    ]
