# Generated by Django 6.0.5 on 2026-06-06 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_modelo_completo_y_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
