# Generated by Django 6.1 on 2026-08-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0003_trabajador_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'db_table': 'cronograma',
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turno', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Guardia',
                'verbose_name_plural': 'Guardias',
                'db_table': 'guardia',
            },
        ),
        migrations.CreateModel(
            name='AprobacionCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('cronograma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion', to='guardias.cronograma')),
            ],
            options={
                'verbose_name': 'Aprobación de Cronograma',
                'verbose_name_plural': 'Aprobaciones de Cronogramas',
            },
        ),
        migrations.CreateModel(
            name='AsignacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.cronograma')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.guardia')),
            ],
            options={
                'verbose_name': 'Asignación de Guardia',
                'verbose_name_plural': 'Asignaciones de Guardias',
                'db_table': 'asignacionguardia',
            },
        ),
    ]
