# Generated by Django 6.0.5 on 2026-09-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_seguridad_bloqueos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login exitoso'), ('login_failed', 'Login fallido'), ('access_denied', 'Acceso denegado'), ('user_deleted', 'Usuario eliminado')], db_index=True, max_length=20),
        ),
    ]
