# Generated by Django 6.0.5 on 2026-09-25 21:13

import trabajadores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_modelo_completo_y_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cedula',
            field=models.CharField(help_text='Formato: V-12345678 o E-1234567 (7 u 8 dígitos).', max_length=10, unique=True, validators=[trabajadores.validators.validar_cedula_venezuela]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
