# Generated by Django 6.0.5 on 2026-09-27 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'El nombre del cargo es demasiado corto.')]),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'El nombre de la especialidad es demasiado corto.')]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
