# Generated by Django 6.0.5 on 2026-07-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores_ext', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditoriatrabajador',
            new_name='trabajadore_creado__936930_idx',
            old_name='trabajador_ext_aud_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriatrabajador',
            new_name='trabajadore_tabla_b9f99c_idx',
            old_name='trabajador_ext_tab_idx',
        ),
    ]
